{
 "title": "Network Indexing",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "network",
    "query": "mainnet,ropsten,rinkeby,kovan,goerli,poa-core"
   }
  ]
 },
 "panels": [
  {
   "title": "Indexing Health",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "time() - network_ethereum_[[network]]_v0_last_new_chain_head_time",
     "legendFormat": "Last new chain head"
    },
    {
     "expr": "time() - network_ethereum_[[network]]_v0_last_written_block_time",
     "legendFormat": "Last written block"
    }
   ]
  },
  {
   "title": "Blocks behind",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_chain_head - network_ethereum_[[network]]_v0_local_head",
     "legendFormat": "Currently"
    }
   ]
  },
  {
   "title": "Chain head vs. local head",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_chain_head",
     "legendFormat": "Chain head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_local_head",
     "legendFormat": "Local head"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_sync_total_secs",
     "legendFormat": "Total"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_blocks_secs",
     "legendFormat": "Fetch blocks"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_unknown_secs",
     "legendFormat": "Unknown"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_chain_head_secs",
     "legendFormat": "Chain head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_subgraph_head_secs",
     "legendFormat": "Subgraph head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_transact_block_secs",
     "legendFormat": "Transact block"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_index_range_secs",
     "legendFormat": "Index block range"
    }
   ]
  },
  {
   "title": "Reorgs in time range",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(network_ethereum_[[network]]_v0_reorg_count[$__range])"
    }
   ]
  },
  {
   "title": "Potential problems",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_poll_chain_head_problems",
     "legendFormat": "Poll chain head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_number_problems",
     "legendFormat": "Fetch block by number (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_hash_problems",
     "legendFormat": "Fetch block by hash"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_full_block_problems",
     "legendFormat": "Fetch full block (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_ommers_problems",
     "legendFormat": "Fetch ommers (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_local_head_problems",
     "legendFormat": "Fetch ommers (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_collect_reorg_data_problems",
     "legendFormat": "Collect reorg ata (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_new_blocks_problems",
     "legendFormat": "Fetch new blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_find_common_ancestor_problems",
     "legendFormat": "Find common ancestor (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_parent_block_problems",
     "legendFormat": "Load parent block (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_revert_blocks_problems",
     "legendFormat": "Revert blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_write_block_problems",
     "legendFormat": "Write block"
    }
   ]
  },
  {
   "title": "Reorgs",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_reorg_count",
     "legendFormat": "Number of reorgs"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_reorg_cancel_count",
     "legendFormat": "Number of canceled reorgs"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_reorg_depth_avg",
     "legendFormat": "Average reorg depth"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_reorg_depth_cur",
     "legendFormat": "Latest reorg depth"
    }
   ]
  },
  {
   "title": "Indexing rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(network_ethereum_[[network]]_v0_write_block_count[$__range])",
     "legendFormat": "Blocks/s (time range)"
    },
    {
     "expr": "rate(network_ethereum_[[network]]_v0_write_block_count[10m])",
     "legendFormat": "Blocks/s (over 10 mins)"
    }
   ]
  },
  {
   "title": "Last time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_poll_chain_head_cur",
     "legendFormat": "Poll chain head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_number_cur",
     "legendFormat": "Fetch block by number (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_hash_cur",
     "legendFormat": "Fetch block by hash"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_full_block_cur",
     "legendFormat": "Fetch full block (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_ommers_cur",
     "legendFormat": "Fetch ommers (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_local_head_cur",
     "legendFormat": "Load local head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_collect_reorg_data_cur",
     "legendFormat": "Collect reorg data (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_new_blocks_cur",
     "legendFormat": "Fetch new blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_find_common_ancestor_cur",
     "legendFormat": "Find common ancestor (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_parent_block_cur",
     "legendFormat": "Load parent block (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_revert_blocks_cur",
     "legendFormat": "Revert blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_write_block_cur",
     "legendFormat": "Write block"
    }
   ]
  },
  {
   "title": "Average time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_poll_chain_head_avg",
     "legendFormat": "Poll chain head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_number_avg",
     "legendFormat": "Fetch block by number (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_hash_avg",
     "legendFormat": "Fetch block by hash"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_full_block_avg",
     "legendFormat": "Fetch full block (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_ommers_avg",
     "legendFormat": "Fetch ommers (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_local_head_avg",
     "legendFormat": "Load local head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_collect_reorg_data_avg",
     "legendFormat": "Collect reorg data (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_new_blocks_avg",
     "legendFormat": "Fetch new blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_find_common_ancestor_avg",
     "legendFormat": "Find common ancestor (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_parent_block_avg",
     "legendFormat": "Load parent block (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_revert_blocks_avg",
     "legendFormat": "Revert blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_write_block_avg",
     "legendFormat": "Write block"
    }
   ]
  },
  {
   "title": "Total time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_poll_chain_head_sum",
     "legendFormat": "Poll chain head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_number_sum",
     "legendFormat": "Fetch block by number (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_hash_sum",
     "legendFormat": "Fetch block by hash"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_full_block_sum",
     "legendFormat": "Fetch full block (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_ommers_sum",
     "legendFormat": "Fetch ommers (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_local_head_sum",
     "legendFormat": "Load local head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_collect_reorg_data_sum",
     "legendFormat": "Collect reorg data (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_new_blocks_sum",
     "legendFormat": "Fetch new blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_find_common_ancestor_sum",
     "legendFormat": "Find common ancestor (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_parent_block_sum",
     "legendFormat": "Load parent block (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_revert_blocks_sum",
     "legendFormat": "Revert blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_write_block_sum",
     "legendFormat": "Write block"
    }
   ]
  },
  {
   "title": "Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "network_ethereum_[[network]]_v0_poll_chain_head_count",
     "legendFormat": "Poll chain head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_number_count",
     "legendFormat": "Fetch block by number (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_block_by_hash_count",
     "legendFormat": "Fetch block by hash"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_full_block_count",
     "legendFormat": "Fetch full block (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_ommers_count",
     "legendFormat": "Fetch ommers (parallel)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_local_head_count",
     "legendFormat": "Load local head"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_collect_reorg_data_count",
     "legendFormat": "Collect reorg data (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_fetch_new_blocks_count",
     "legendFormat": "Fetch new blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_find_common_ancestor_count",
     "legendFormat": "Find common ancestor (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_load_parent_block_count",
     "legendFormat": "Load parent block (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_revert_blocks_count",
     "legendFormat": "Revert blocks (reorg)"
    },
    {
     "expr": "network_ethereum_[[network]]_v0_write_block_count",
     "legendFormat": "Write block"
    }
   ]
  }
 ]
}