global:
  scrape_interval: 1s
  evaluation_interval: 1s

rule_files:

scrape_configs:
  - job_name: graph-node-local
    static_configs:
      - targets: ['hostnet:8040']  # `hostnet` is defined in docker-compose.instrumentation.yml
