{
 "title": "Errors and Alerts",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "featured_subgraph_ids",
    "query": "select deployments.id as \"depoymentId\"\n  from subgraphs.subgraph_deployment as deployments\n  join subgraphs.subgraph_version subgraphversions\n       on subgraphversions.deployment=deployments.id\n  join subgraphs.subgraph subgraphs\n       on subgraphs.id=subgraphversions.subgraph\n where subgraphs.name in ('molochventures/moloch', 'ensdomains/ens', 'graphprotocol/compound-v2','graphprotocol/uniswap','livepeer/livepeer','graphprotocol/decentraland','melonproject/melon','betoken/betoken-v1','centrehq/usdc','zeframlou/pooled-cdai','daostack/alchemy','protofire/makerdao-governance')\n group by 1;"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<center>\n  <h1>Subgraph Errors</h1>\n</center>"
  },
  {
   "title": "Failed, Synced Subgraphs",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  subgraphs.name,\n  deployments.id as depoyment_id,\n  sdas.node_id as node_assignment,\n  deployments.entity_count,\n  TIMESTAMP WITH TIME ZONE 'epoch' + (subgraphs.created_at)::numeric * INTERVAL '1 second' as time\nFROM subgraphs.subgraph_deployment deployments\nJOIN subgraphs.subgraph_version subgraphversions\n     ON subgraphversions.deployment=deployments.id\nJOIN subgraphs.subgraph subgraphs\n     ON subgraphs.id=subgraphversions.subgraph\nJOIN subgraphs.subgraph_deployment_assignment sdas\n     ON sdas.id=deployments.id\nWHERE \n    sdas.node_id NOT LIKE '%community%' and \n    deployments.synced and\n    deployments.failed and\n    subgraphversions.id = subgraphs.current_version\nORDER BY subgraphs.created_at desc;"
    }
   ]
  },
  {
   "title": "Postgres Connection Errors",
   "type": "graph",
   "description": "Count of the Postgres connection errors observed",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(store_connection_error_count[5m])"
    }
   ]
  },
  {
   "title": "Synced, Quarantined Subgraph Failure",
   "type": "graph",
   "description": "Filtered to only subgraphs that were deployed to current versions of subgraphs that are deployed to non-community nodes.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select time, 'failed synced-subgraphs' as metric, sum(count) as value\nfrom (\n  select subgraphs.name, now() - interval '5 minutes' as time, 1 as count\n    from subgraphs.subgraph_deployment as deployments\n    join subgraphs.subgraph_version subgraphversions\n         on subgraphversions.deployment=deployments.id\n    join subgraphs.subgraph subgraphs\n         on subgraphs.id=subgraphversions.subgraph\n    join subgraphs.subgraph_deployment_assignment sdas\n         on sdas.id=deployments.id\n   where sdas.node_id NOT LIKE '%community%'\n     and deployments.synced\n     and deployments.failed\n     and subgraphversions.id = subgraphs.current_version) failures\ngroup by time, metric"
    }
   ]
  },
  {
   "title": "HighViz Subgraphs' errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "level:error AND arguments.id:(\\\"QmaHmvnYRMohztuqChRWKEuC2uvJrHuSoxdgRVy1F8ckce\\\" OR \\\"QmanfvYz5bMSFkxxAX4JgDuHGE8hy3RYYE8w2pa3c9uWQh\\\" OR \\\"Qmb7e8bYoj93F9u33R3JY1H764626C8KHUgWMeVjWPiwdD\\\" OR \\\"Qmbrr6bzB3t3CLWeeFEwbGf5Bg7uxqSXsKNmw5CvCWuN7o\\\" OR \\\"Qmc5NVBRrrL7EpNyRwv4QjyKBUzRJD4uV3unxcBSo9Wfxu\\\" OR \\\"QmcBSszwkBdGVXGARthtVgLD7TqcjB5NmJykx4Jah4sHUh\\\" OR \\\"QmdZJb8qdUhzgyrvApqFQanBkrF99BUzELYXBNDpGcDq73\\\" OR \\\"QmeQJg5hH9UfZzgbfqa4SMrjkGo1HQwqCuGuUdbFT89qDL\\\" OR \\\"QmeWj9LPVY2XJGGiXV5DwRyihoftjWHU9Zra674tmfyRng\\\" OR \\\"QmNrxPs2GR7h6EF2MYbqALBDMYPpsNQw6SRm63EojQpqoe\\\" OR \\\"QmQe1UFi2srsXoVTRiAL8heNMFU6XbDEYhygniDMYmaiek\\\" OR \\\"QmQGM4j9v8p1QxoSCeQysLR5v4kAUUZQraYjHtMDUkCT2R\\\" OR \\\"QmRcC3eUJ1UooYq7zDqxcCZhMynEj2RaqWPizRNAxjdSs4\\\" OR \\\"QmSsGyDuzdJwD4mMEGzEg71mkbi9HWADVYmBgimgrMHQVs\\\" OR \\\"QmT36xUZbXRyvy7kfDVMwFpgvKVkhzRp2vAeM532sY3bH3\\\" OR \\\"QmTVj5UrfYDLtAaJFj7zf2RDoRgfhBJNTZxHfqfrqoWppm\\\" OR \\\"QmVEoWSQ8eNnVkL1uw2toDSc1xXKi1ADYUm36p961Q1EzT\\\" OR \\\"QmXEgDQGY1mXTmwnS3hgLcVDXncLuJEbaYFqnJoyGDCNe5\\\" OR \\\"QmXrCYiz6KbG9WAZhZTbgUw8F1GQRVGdk2cdnY6kFXvAtx\\\" OR \\\"QmYFFi6Dj3tJLPPg1im15hgFoNeysP31DWFFMEqNRbD6MS\\\" OR \\\"QmZ94ksbk8XjeV4H21EcbS7aQxRtYSw6bVXakgRX6JABhb\\\" OR \\\"QmZTHHbtEyGcDRp2mWiuSHMKU1PrHKh7KaMp1jDPSNDqRv\\\")",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Featured Subgraphs' errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "level:error AND arguments.id:($featured_subgraph_ids)",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Errors by subgraph",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "subgraphId.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "level:error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Subgraph errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "level:error",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 51 },
   "content": "<center>\n  <h1>Block Ingestor Syncing</h1>\n</center>"
  },
  {
   "title": "Mainnet: Blocks Syncing ",
   "type": "graph",
   "description": "Expects at least 18 block syncing logs per 5 minute interval.  (average block time = ~15 seconds)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{network=\"mainnet\",kubernetes_pod_name=\"index-node-block-ingestor-0\"}[5m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Kovan: Blocks Syncing ",
   "type": "graph",
   "description": "Expects at least 70 block syncing logs per 5 minute interval. (average block time = 4 seconds)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{network=\"kovan\",kubernetes_pod_name=\"index-node-block-ingestor-0\"}[5m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Rinkeby: Blocks Syncing ",
   "type": "graph",
   "description": "Expects at least 19 block syncing logs per 5 minute interval. (average block time = 15 seconds)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{network=\"rinkeby\",kubernetes_pod_name=\"index-node-block-ingestor-0\"}[5m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Goerli: Blocks Syncing  (prom)",
   "type": "graph",
   "description": "Expects at least 19 block syncing logs per 5 minute interval. (average block time = ~15 seconds)",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{network=\"goerli\",kubernetes_pod_name=\"index-node-block-ingestor-0\"}[5m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Ropsten: Blocks Syncing ",
   "type": "graph",
   "description": "Expects at least 6 block syncing logs per 5 minute interval. (average block time < 30 seconds, but allowing some headroom)",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{network=\"ropsten\",kubernetes_pod_name=\"index-node-block-ingestor-0\"}[10m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Poa-core: Blocks Syncing ",
   "type": "graph",
   "description": "Expects at least 50 block syncing logs per 5 minute interval. (average block time = ~5 seconds)",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(ethereum_chain_head_number{network=\"poa-core\",kubernetes_pod_name=\"index-node-block-ingestor-0\"}[5m])",
     "legendFormat": "{{network}}"
    }
   ]
  },
  {
   "title": "Subgraphs that have neither started nor failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "select now() as time, count(*) as num_subgraphs\n   from (\n   select d.id, d.latest_ethereum_block_number block\n     from subgraphs.subgraph_deployment d,\n          subgraphs.subgraph_deployment_assignment a\n    where d.id = a.id\n    and not d.failed) a\n   where a.block < 100;\n"
    }
   ]
  },
  {
   "title": "Network Blocks Syncing (from ES logs)",
   "type": "graph",
   "description": "Expects at least 50 block syncing logs per 5 minute interval. (average block time = ~5 seconds)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "arguments.network_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "timestamp", "id": "2", "settings": { "interval": "5m", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "meta.module:\"graph_chain_ethereum::block_ingestor\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 83 },
   "content": "<center>\n  <h1>Web3</h1>\n</center>"
  },
  {
   "title": "Alchemy API Rate Limited",
   "type": "graph",
   "description": "Tracks the number of web3 requests that were rejected due to rate limiting. ",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "text:\"429 Too Many Requests\"",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "All errors: text",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "subgraphId.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "text.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "level:error",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}